#!/usr/bin/env bun
import { extractVideoId } from "./src/utils";
import { fetchTranscript } from "./src/transcript";
import { format, type Format } from "./src/formatters";

function parseArgs(argv: string[]) {
  const args = argv.slice(2); // skip bun and script path
  let url: string | undefined;
  let lang: string | undefined;
  let fmt: Format = "txt";
  let output: string | undefined;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--lang" && args[i + 1]) {
      lang = args[++i];
    } else if (arg === "--format" && args[i + 1]) {
      const val = args[++i] as Format;
      if (!["txt", "srt", "json"].includes(val)) {
        console.error(`Invalid format "${val}". Supported: txt, srt, json`);
        process.exit(1);
      }
      fmt = val;
    } else if (arg === "--output" && args[i + 1]) {
      output = args[++i];
    } else if (arg === "--help" || arg === "-h") {
      printUsage();
      process.exit(0);
    } else if (!arg.startsWith("--")) {
      url = arg;
    }
  }

  return { url, lang, fmt, output };
}

function printUsage() {
  console.log(`
Usage: bun run index.ts <youtube-url> [options]

Options:
  --lang <code>       Language code (e.g., en, es, fr). Default: auto-detect
  --format <fmt>      Output format: txt, srt, json. Default: txt
  --output <path>     Output file path. Default: <videoId>.<format>
  -h, --help          Show this help message

Examples:
  bun run index.ts https://www.youtube.com/watch?v=dQw4w9WgXcQ
  bun run index.ts dQw4w9WgXcQ --format srt
  bun run index.ts https://youtu.be/dQw4w9WgXcQ --lang es --output transcript.txt
`.trim());
}

async function main() {
  const { url, lang, fmt, output } = parseArgs(Bun.argv);

  if (!url) {
    printUsage();
    process.exit(1);
  }

  const videoId = extractVideoId(url);
  console.log(`Fetching transcript for: ${videoId}...`);

  const result = await fetchTranscript(videoId, lang);
  const content = format(result, fmt);
  const filePath = output ?? `${videoId}.${fmt}`;

  await Bun.write(filePath, content);

  console.log(`Title: ${result.title}`);
  console.log(`Language: ${result.language}${result.isAutoGenerated ? " (auto-generated)" : ""}`);
  console.log(`Segments: ${result.segments.length}`);
  console.log(`Saved to: ${filePath}`);
}

main().catch((err) => {
  console.error(`Error: ${err.message}`);
  process.exit(1);
});
