export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptResult {
  videoId: string;
  title: string;
  language: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name: { simpleText?: string; runs?: { text: string }[] };
}

const WEB_USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const ANDROID_USER_AGENT =
  "com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip";

/**
 * Step 1: Fetch the video page to extract cookies and the INNERTUBE_API_KEY
 */
async function fetchVideoPage(videoId: string) {
  const url = `https://www.youtube.com/watch?v=${videoId}`;
  const res = await fetch(url, {
    headers: {
      "User-Agent": WEB_USER_AGENT,
      "Accept-Language": "en-US,en;q=0.9",
    },
  });

  if (!res.ok) {
    throw new Error(`Failed to fetch video page: ${res.status}`);
  }

  const html = await res.text();

  // Extract cookies from response for session continuity
  const cookies = res.headers.getSetCookie?.() ?? [];
  const cookieStr = cookies.map((c) => c.split(";")[0]).join("; ");

  // Extract API key
  const apiKeyMatch = html.match(
    /"INNERTUBE_API_KEY":\s*"([a-zA-Z0-9_-]+)"/
  );
  if (!apiKeyMatch) {
    throw new Error(
      `Could not extract API key for video "${videoId}". The video may be unavailable or access is blocked.`
    );
  }

  return { apiKey: apiKeyMatch[1], cookies: cookieStr };
}

/**
 * Step 2: Call Innertube player endpoint with ANDROID client context
 * This returns caption URLs without exp=xpe restriction
 */
async function fetchPlayerData(
  videoId: string,
  apiKey: string,
  cookies: string
) {
  const res = await fetch(
    `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent": ANDROID_USER_AGENT,
        Cookie: cookies,
      },
      body: JSON.stringify({
        context: {
          client: {
            clientName: "ANDROID",
            clientVersion: "20.10.38",
          },
        },
        videoId,
      }),
    }
  );

  if (!res.ok) {
    throw new Error(`Innertube API returned ${res.status}: ${res.statusText}`);
  }

  return res.json();
}

function selectCaptionTrack(
  tracks: CaptionTrack[],
  language?: string
): CaptionTrack {
  if (language) {
    const match = tracks.find((t) => t.languageCode === language);
    if (match) return match;

    const available = tracks.map((t) => t.languageCode).join(", ");
    throw new Error(
      `Language "${language}" not available. Available: ${available}`
    );
  }

  // Prefer manual captions over auto-generated
  const manual = tracks.find((t) => t.kind !== "asr");
  return manual ?? tracks[0];
}

function getTrackName(track: CaptionTrack): string {
  if (track.name.simpleText) return track.name.simpleText;
  if (track.name.runs) return track.name.runs.map((r) => r.text).join("");
  return track.languageCode;
}

/**
 * Step 3: Fetch and parse the caption XML
 */
async function fetchCaptionXml(baseUrl: string): Promise<TranscriptSegment[]> {
  // Remove fmt=srv3 if present (we want default XML)
  const url = baseUrl.replace("&fmt=srv3", "");

  const res = await fetch(url, {
    headers: { "User-Agent": WEB_USER_AGENT },
  });

  if (!res.ok) {
    throw new Error(`Failed to fetch captions: ${res.status}`);
  }

  const xml = await res.text();
  if (!xml || xml.length === 0) {
    throw new Error("Caption response was empty");
  }

  return parseXmlTranscript(xml);
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'");
}

function parseXmlTranscript(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const regex = /<text start="([^"]*)" dur="([^"]*)"[^>]*>([\s\S]*?)<\/text>/g;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(xml)) !== null) {
    const start = parseFloat(match[1]);
    const duration = parseFloat(match[2]);
    // Strip HTML tags and decode entities
    const text = decodeHtmlEntities(match[3].replace(/<[^>]*>/g, ""))
      .replace(/\n/g, " ")
      .replace(/\s+/g, " ")
      .trim();
    if (text.length > 0) {
      segments.push({ text, start, duration });
    }
  }

  return segments;
}

export async function fetchTranscript(
  videoId: string,
  language?: string
): Promise<TranscriptResult> {
  // Step 1: Get page cookies and API key
  const { apiKey, cookies } = await fetchVideoPage(videoId);

  // Step 2: Get player data with ANDROID client
  const player = await fetchPlayerData(videoId, apiKey, cookies);

  const status = player.playabilityStatus?.status;
  if (status !== "OK") {
    const reason = player.playabilityStatus?.reason ?? "Unknown reason";
    throw new Error(`Video "${videoId}" is not playable: ${reason}`);
  }

  const title =
    player.videoDetails?.title ??
    player.microformat?.playerMicroformatRenderer?.title?.simpleText ??
    "Unknown";

  const tracks: CaptionTrack[] | undefined =
    player.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!tracks || tracks.length === 0) {
    throw new Error(
      `No captions available for video "${videoId}". The video may not have subtitles.`
    );
  }

  const track = selectCaptionTrack(tracks, language);

  // Step 3: Fetch caption data
  const segments = await fetchCaptionXml(track.baseUrl);

  return {
    videoId,
    title,
    language: getTrackName(track),
    isAutoGenerated: track.kind === "asr",
    segments,
  };
}
